language: go

go:
- 1.10.x
os:
- linux

before_install:
- go get github.com/golang/dep/cmd/dep
- sudo apt-get update -qq && sudo apt-get install libsnappy-dev zlib1g-dev libbz2-dev -qq
- wget https://launchpad.net/ubuntu/+archive/primary/+files/libgflags2_2.0-1.1ubuntu1_amd64.deb
- sudo dpkg -i libgflags2_2.0-1.1ubuntu1_amd64.deb
- wget https://launchpad.net/ubuntu/+archive/primary/+files/libgflags-dev_2.0-1.1ubuntu1_amd64.deb
- sudo dpkg -i libgflags-dev_2.0-1.1ubuntu1_amd64.deb


install:
- git clone https://github.com/bitcoin-core/secp256k1.git /tmp/secp256k1
- pushd /tmp/secp256k1
- ./autogen.sh
- ./configure
- make
- sudo make install
- cd -
- dep ensure

script:
- make build
- go test ./... -tags=integration