
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "github.com/asaskevich/EventBus"

[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/btcutil"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "1.2.1"

[[constraint]]
  branch = "master"
  name = "github.com/golang-collections/collections"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.3.1"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.3.1"

[[constraint]]
  name = "github.com/hashicorp/golang-lru"
  version = "0.5.1"

[[constraint]]
  name = "github.com/jinzhu/copier"
  revision = "7e38e58719c33e0d44d585c4ab477a30f8cb82dd"

[[constraint]]
  name = "github.com/libp2p/go-libp2p"
  version = "=0.2.1"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-core"
  version = "=0.2.2"
  
[[override]]	
  name = "github.com/libp2p/go-mplex"		
  version = "=0.1.0"	

[[constraint]]
  name = "github.com/libp2p/go-libp2p-crypto"
  version = "=0.1.0"

[[override]]
  name = "github.com/libp2p/go-ws-transport"
  version = "0.2.0"

[[override]]
name = "github.com/libp2p/go-eventbus"
version = "0.1.0"

[[constraint]]
  name = "github.com/multiformats/go-multiaddr"
  version = "0.2.0"

[[override]]
  name = "github.com/multiformats/go-multiaddr-dns"
  version = "0.2.0"

[[constraint]]
  name = "github.com/peterh/liner"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/raviqqe/hamt"

[[constraint]]
  branch = "master"
  name = "github.com/rcrowley/go-metrics"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/shirou/gopsutil"
  version = "2.19.5"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "github.com/syndtr/goleveldb"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.21.1"

[[override]]
  name = "github.com/ipfs/go-log"
  #branch = "master"
  #revision = "c50c291a61bceccb914366d93eb24f58594e9134"
  version = "0.0.1"
